application: gu-text-catcher
version: 12
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /api/.*
  script: api.app
- url: /archive
  script: archive.app
- url: /archive/.*
  script: archive.app
- url: /admin/.*
  script: admin.app
  login: admin
- url: /tasks/.*
  script: tasks.app
  login: admin
- url: /.*
  script: app.app

libraries:
- name: jinja2
  version: latest

builtins:
- remote_api: on