application: gu-text-catcher
version: 6
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /api/.*
  script: api.app
- url: /.*
  script: app.app

libraries:
- name: jinja2
  version: latest